### ISSUE TITLE
About the ppp metric computation

### ISSUE THREAD

**Issue by YuhaoCheng** [haochen-rye/HNeRV#3]
Thanks for your great work in representing the video.  

I notice that you use the pixel-for-pixel (PPP) to measure the compactness of the model; however, as a result, that I'm a freshman in this area, and I'm confused about how to compute the PPP. So would you mind explaining more about this metric, or directly updating the code to compute this metric? I would appreciate it if you could do these.

Thanks for your time again.

**Comment by haochen-rye** [comment]
Sorry for the late reply.
Will update the code to include PPP computation. 
For the PPP definition, I use **parameter per pixel** to evaluate the efficiency of implicit representation, which is HNeRV_parameters / video_pixel_num.

**Comment by YuhaoCheng** [comment]
Thanks for your kind reply, and it's helpful. I am looking forward to your update.
