### ISSUE TITLE
Raw or MP4 format?

### ISSUE THREAD

**Issue by tuanlda78202** [haochen-rye/HNeRV#9]
Dear @haochen-rye,

I hope this letter finds you well. First and foremost, I would like to extend my appreciation for the outstanding work you have been doing. 🤗

I am writing to inquire about the UVG dataset and its testing procedures. Specifically, I am interested to know whether you conduct tests on raw YUV videos or MP4 videos. As far as my understanding goes, the UVG dataset is in raw format and compressed. However, I am aware that when reading video files, the matrices representing the channel data will be the same, regardless of the file format.

In my search for NeRV-based papers, I have been unable to locate any code files that demonstrate how to read raw video files. Could you kindly provide clarification on this matter or direct me to relevant resources?

Thank you for your time and attention to this matter. I genuinely appreciate any insights you can share. Wishing you a wonderful day and looking forward to hearing from you soon.

Sincerely,
Charles

**Comment by haochen-rye** [comment]
Hi Charles,

Thanks for your interest and question.
For UVG videos, I firstly extract PNG frames from raw YUV videos with cmd like `'ffmmpeg -i *.yuv %04d.png'`; then all following processes are based on these PNG frames.
